### ISSUE TITLE
Game freezes while loading world

### ISSUE THREAD

**Issue by grylliade** [Lothrazar/GameRuleConfig#1]
Minecraft Version: 1.16.2

Forge Version: 33.0.10

Mod Version: 1.0.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): While trying to create a new world, the game freezes at 47% loaded, and I have to kill the process with Task Manager. This has happened at the same point multiple times, both with other mods and with this as the only mod, and with resource packs loaded and without.

Log file link: https://drive.google.com/file/d/1s1fMj3LZtMsG25J8XPsTjnKYzGtxk5NB/view?usp=sharing

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
looking into it

**Comment by Lothrazar** [comment]
fixed in 1.16.3 https://www.curseforge.com/minecraft/mc-mods/custom-game-rules/files/3105223
