### ISSUE TITLE
The disabledecaycoral gamerule doesnt work

### ISSUE THREAD

**Issue by Blugori** [Lothrazar/GameRuleConfig#2]
Minecraft Version: 1.16.3

Forge Version: 34.1.19

Mod Version: customgamerules-1.16.3-1.0.1.jar

Single Player or Server: single player

I just tried the disabledecaycoral (/gamerule disabledecaycoral true), but the coral kept decaying outside of water :/

Log file link:
[latest.log](https://github.com/Lothrazar/CustomGameRules/files/5384000/latest.log)

**Comment by Lothrazar** [comment]
Thanks for the report. yeah same bug happens with the ice melting rule.  

Except. they all just fine when the mod is installed by itself with nothing else. but when i update forge and run it in a back with a ton of mods, then it does nothing.  


Some sort of conflict i have to figure out

**Comment by Blugori** [comment]
I'm currently trying the mod in 1.16.4 with forge 35.0.7, without any other mod (even without optifine), and the gamerule doesn't work :/ 
Could forge be the problem here ?

**Comment by Lothrazar** [comment]
Fixed in new version, please report if it breaks again https://www.curseforge.com/minecraft/mc-mods/custom-game-rules/files/3151504
