### ISSUE TITLE
Ticking entity crash with Ghast fireballs

### ISSUE THREAD

**Issue by mortuusars** [Lothrazar/GameRuleConfig#3]
- Minecraft Version: 1.16.3
- Forge Version: 34.1.25
- Mod Version: 1.0.1
- Single Player

Game crashes after ghast fireball explodes. Not from the first explosion, after 1-2.
I have changed only "doFireTick" and "mobGriefingCreeper" to false. Everything else is default.

Log file link:
https://paste.ee/p/LH2VQ

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/custom-game-rules/files/3105223
