### ISSUE TITLE
Server Incompatible? Failing to launch.

### ISSUE THREAD

**Issue by ClassyNinja** [Lothrazar/GameRuleConfig#4]
Minecraft Version: 1.16.3

Forge Version: 1.16.3-34.1.0

Mod Version: 1.16.3-1.0.1

Single Player or Server: Server

Describe the problem (what you were doing; what happened; what should have happened):
The server is failing to launch, the error below;

> Failure message: Powerful Game Rules (customgamerules) encountered an error during the common_setup event phase
>                 java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER

Log file link:
Latest.log and Debug.log files: https://paste.ee/p/Nkx2P

**Comment by Lothrazar** [comment]
Working on it :)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/custom-game-rules/files/3105223
