### ISSUE TITLE
The mobGriefingGhast command does not work

### ISSUE THREAD

**Issue by ClassyNinja** [Lothrazar/GameRuleConfig#5]
Edit: Updated the server and forge to 1.16.4 - the issue still persists.

Hi Lothrazar, thanks for fixing the last issue I logged so quickly!

Minecraft Version: ~~1.16.3~~ 1.16.4

Forge Version: ~~1.16.3-34.1.0~~ 1.16.4-35.0.14

Mod Version: 1.16.3-1.0.2

Single Player or Server: Both Single and Server

Describe the problem (what you were doing; what happened; what should have happened):
Ghasts are still able to destroy blocks with the command: /gamerule mobGriefingGhast false

**Comment by Lothrazar** [comment]
Fixed in new version, please report if it breaks again https://www.curseforge.com/minecraft/mc-mods/custom-game-rules/files/3151504
