### ISSUE TITLE
disable gravity not working

### ISSUE THREAD

**Issue by stevojhall** [Lothrazar/GameRuleConfig#6]
Minecraft Version: 1.16.4

Forge Version: 35.0.14 

Mod Version: 1.02

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened): Disable blocks falling from gravity - on does not stop gravel and sand from falling from block update

Log file link: no log (does log file report block falling triggered? if so I can try to locate it) 

Video/images/gifs (direct upload or link):  none

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Fixed in new version, please report if it breaks again https://www.curseforge.com/minecraft/mc-mods/custom-game-rules/files/3151504
