### ISSUE TITLE
Port this Mod to Fabric?

### ISSUE THREAD

**Issue by Zockerhopper** [Lothrazar/GameRuleConfig#8]
Minecraft Version: 1.16.4

Now I'm not the Greatest with Mods but at first I thought Mixins were Fabric only thus I thought this Mod was for Fabric.
Now of course I notice that that Mod is not registered in Mod Menu. Because of that I wanted to ask if you could Port this to Fabric? Would be pretty Great!

**Comment by Lothrazar** [comment]
I barely even know what fabric is. i know that it exists and not many people use it.

I would accept a pull request porting it to fabric if you or anyone wanted to do it.  if so i would create a new curse page and help with support if possible.  <3

But im too busy and lazy to learn a whole new API for a handful of users.
